# Generated by Django 3.2.8 on 2021-12-08 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211205_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='main.albums', verbose_name='Альбом'),
        ),
    ]
